# Generated by Django 4.2.27 on 2026-01-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0002_remove_tagmodel_article'),
        ('Post', '0002_alter_article_id_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='Tags.tagmodel'),
        ),
    ]
