# Generated by Django 4.2.27 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_article_image_alter_article_id_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Article/'),
        ),
    ]
