# Generated by Django 5.2.6 on 2025-09-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeStories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='LifeStories.categories'),
        ),
    ]
